{
 "title": "Infrastructure — Supervision",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode='idle'}[2m])) * 100)",
     "legendFormat": "CPU {{instance}}"
    }
   ]
  },
  {
   "title": "RAM disponible %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "RAM dispo {{instance}}"
    }
   ]
  },
  {
   "title": "Services UP/DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}